### ISSUE TITLE
Crashing when hit at the same time as teleporting between dimensions

### ISSUE THREAD

**Issue by Grossley** [CodedSakura/FabricTPA#16]
Log of crash
```
[14:56:36] [Timer-78/INFO]: [STDERR]: java.lang.IllegalStateException: Removing entity while ticking!
[14:56:36] [Timer-78/INFO]: [STDERR]: at net.minecraft.class_3218.method_18774(class_3218.java:942)
[14:56:36] [Timer-78/INFO]: [STDERR]: at net.minecraft.class_3218.method_18770(class_3218.java:958)
[14:56:36] [Timer-78/INFO]: [STDERR]: at net.minecraft.class_3222.method_14251(class_3222.java:1440)
[14:56:36] [Timer-78/INFO]: [STDERR]: at eu.codedsakura.fabrictpa.FabricTPA$1.run(FabricTPA.java:431)
[14:56:36] [Timer-78/INFO]: [STDERR]: at java.util.TimerThread.mainLoop(Timer.java:555)
[14:56:36] [Timer-78/INFO]: [STDERR]: at java.util.TimerThread.run(Timer.java:505)
```

**Comment by CodedSakura** [comment]
should be fixed in 2.0.0
